### PR TITLE
Add a property to configure the distribution strategy of keys

### PR DESCRIPTION
**Pull request by jucham**
Hi,

I really liked your spring boot integration because that made my life easier! Thank you for that! There is just one little thing missing I would like to have : be able to choose consistent hashing as algorithm for distribution of keys between servers. That's what my PR is about. Tell me what you think about it.

Julien

### CODE REVIEW

**Comment by igorbolic** [comment]
Thank you for the PR, looks great 👍  This is something that could be useful to add as configuration option. I'll put my remarks on the PR...

**Comment by jucham** [comment]
You're right, it's a good idea to take account the other options. I made the changes you suggested, however by digging a little I could see that these different options are configurable. For example, 
`KetamaMemcachedSessionLocator(HashAlgorithm alg, boolean cwNginxUpstreamConsistent,
      boolean gwhalinMemcachedJavaClientCompatibiltyConsistent)`
Would you expose these parameters or is this too advanced ? To me the default parameters are fine but there again could be useful for someone else. What's your thought ?

**Comment by igorbolic** [comment]
> For example,
> `KetamaMemcachedSessionLocator(HashAlgorithm alg, boolean cwNginxUpstreamConsistent, boolean gwhalinMemcachedJavaClientCompatibiltyConsistent)`
> Would you expose these parameters or is this too advanced ? To me the default parameters are fine but there again could be useful for someone else. What's your thought ?

I would go with the default parameters... While there is a value in being able to choose a hash strategy, I believe it would be convoluted for most of the users to add the other options as well. 

Let's keep it simple for starts, using the default parameters. And if there is a need for additional customization, it can always be added in the future

**Comment by jucham** [comment]
Igor,

Here is the update, keeping the things simple. Tell me if you see something wrong.

**Comment by jucham** [comment]
Great, you're welcome!

**Comment by igorbolic** [comment]
Released with **2.1.0**

**Pull request merged**
